site:
  title: 在路上的官方网站
  description: 在路上的官方网站 (ontheway.com) 分享技术、生活和思考
  keywords: 在路上, ontheway, 技术, 生活, 思考, 博客, 写作
  theme: default
  language: zh-CN
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  root-path: /yourdailyshells.com
  # set cdn prefix: self hosted
  cdn-path: /yourdailyshells.com/static
  navigation:
    - title: Markdown教程(廖雪峰)
      uri: /books/gitsite-guide/index.html
    # - title: 最新
    #   uri: /blogs/all/index.html
    - title: 技术
      uri: /blogs/tech/index.html
    - title: 格局打开
      uri: /blogs/How2MakeMoney/index.html
  git:
    base-url: https://github.com/OnTheWay0103/yourdailyshells.com/blob/main/source
  contact:
    name: 在路上
    github: https://github.com/OnTheWay0103/yourdailyshells.com.git
    twitter: https://twitter.com/ontheway
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: false
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: oauth
      url: https://api.ontheway.com
  #   analytics:
  #     provider: baidu
  #     id: "2efddd14a5f2b304677462d06fb4f964"
  footer: |
    <div>
      &copy;<a href="/">ontheway.com</a> 
      - <a href="https://weibo.com/ontheway" target="_blank">微博</a>
      - <a href="https://github.com/OnTheWay0103/dailyshells.com.git" target="_blank">GitHub</a>
      - <a href="/pages/license/index.html" target="_blank">License</a>
    </div>

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt
# you can add any items:
